### ISSUE TITLE
Missing imports in The Sample Node for using python libraries.

### ISSUE THREAD

**Issue by lewiswhe** [mmmarinho/ROS2_Tutorial#8]
Hi Murilo,

In the node_that_uses_a_library.py file from "The Sample Node", [using_python_library](https://github.com/mmmarinho/ROS2_Tutorial/blob/main/docs/source/using_python_library.rst), I believe there are two missing libraries.

When I run I get the errors
```
name 'random' is not defined
name 'string' is not defined
```

which are fixed by importing their relevant libraries
```
import random, string
```

These imports are present in the hosted file from the download link, but not shown in the code blocks directly below the link as it is reading `:lines: 27-`, a few lines after the two imports.
Changing this to `:lines: 24-` will correctly show the imports

Kind regards,
Lewis

**Comment by mmmarinho** [comment]
Thanks @lewiswhe, fixed in 3d1e58d3957599f79b024bf9f797af39bd05ef40.
